GET http://localhost:5000/seller/beans HTTP/1.1

# GET https://example.com/comments/1 HTTP/1.1

###
POST http://localhost:2900/api/auth/seller
content-type: application/json

{
    "fullName": "Geetico Team",
    "email": "akapatemisan007@gmail.com",
    "password": "productlisting"
}