export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL';

export const APPEND_TO_PRODUCT = 'APPEND_TO_PRODUCT';
export const INIT_ADD_PRODUCT = 'INIT_ADD_PRODUCT';
export const PRODUCT_FETCH_START = 'PRODUCT_FETCH_START';
export const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_CHECK_START = 'AUTH_CHECK_START';
export const AUTH_CHECK_BEFORE_AUTH = 'AUTH_CHECK_BEFORE_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_SUCCESS_NULL = 'SET_SUCCESS_NULL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
