export const AUTH_START = 'AUTH_START';
export const AUTH_CHECK_START = 'AUTH_CHECK_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL';
export const SET_AUTH_MODAL_TO_TRUE = 'SET_AUTH_MODAL_TO_TRUE';
export const AUTH_CHECK_BEFORE_AUTH = 'AUTH_CHECK_BEFORE_AUTH';
export const TELL_USER_TO_VERIFY = 'TELL_USER_TO_VERIFY';
export const SET_REDIRECT_TO_EMAIL_VERIFICATION_PAGE =
  'SET_REDIRECT_TO_EMAIL_VERIFICATION_PAGE';

// CART ACTIONS
export const START_CART_EDIT = 'START_CART_EDIT';
export const ADD_CART_END = 'ADD_CART_END';
export const ADD_CART_FAIL_MESSAGE = 'ADD_CART_FAIL_MESSAGE';
export const ADD_CART_START = 'ADD_CART_START';
export const SET_CART_VALUE = 'SET_CART_VALUE';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const EDIT_CART_QUANTITY = 'EDIT_CART_QUANTITY';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const SHOW_CART_PREVIEW = 'SHOW_CART_PREVIEW';
export const APPEND_PRODUCT_DETAILS_TO_CART_PREVIEW =
  'APPEND_PRODUCT_DETAILS_TO_CART_PREVIEW';

// ORDER ACTIONS
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

// NOTIFICATION ACTIONS

export const GET_NOTIFICATION_COUNT = 'GET_NOTIFICATION_COUNT';
